services:
# MEDIA SERVER  
  plex:
    image: cr.hotio.dev/plex:latest
    container_name: plex
    networks:
      - main
    ports:
      - 32400:32400
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - ADVERTISE_IP=http://192.168.53.232:32400,https://plex.jnbolsen.com
      - ALLOWED_NETWORKS
      - PLEX_PASS=no
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${ROOT_DIR}/docker/plex-config:/config
      - ${SHARE_DIR}/data/media:/data/media
    restart: unless-stopped

  tautulli:
    image: cr.hotio.dev/hotio/tautulli:testing
    container_name: tautulli
    networks:
      - main
    depends_on:
      - plex
    ports:
      - 8181:8181
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/tautulli-config:/config
    restart: unless-stopped


# SERVARR
  radarr1:
    image: cr.hotio.dev/hotio/radarr:nightly
    container_name: radarr1
    networks:
      - main
    ports:
      - 7878:7878
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/radarr1-config:/config
      - ${SHARE_DIR}/data:/data
    restart: unless-stopped

  radarr2:
    image: cr.hotio.dev/hotio/radarr:nightly
    container_name: radarr2
    networks:
      - main
    depends_on:
      - radarr1
    ports:
      - 7879:7878
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/radarr2-config:/config
      - ${SHARE_DIR}/data:/data
    restart: unless-stopped

  sonarr:
    image: cr.hotio.dev/hotio/sonarr:v4
    container_name: sonarr
    networks:
      - main
    ports:
      - 8989:8989
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/sonarr-config:/config
      - ${SHARE_DIR}/data:/data
    restart: unless-stopped

  lidarr:
    image: cr.hotio.dev/hotio/lidarr:nightly
    container_name: lidarr
    networks:
      - main
    ports:
      - 8686:8686
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/lidarr-config:/config
      - ${SHARE_DIR}/data:/data
    restart: unless-stopped

  readarr:
    image: cr.hotio.dev/hotio/readarr:nightly
    container_name: readarr
    networks:
      - main
    ports:
      - 8787:8787
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/readarr-config:/config
      - ${SHARE_DIR}/data:/data
    restart: unless-stopped

  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr:nightly
    container_name: prowlarr
    networks:
      - main
    ports:
      - 9696:9696
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/prowlarr-config:/config
    restart: unless-stopped

  bazarr1:
    container_name: bazarr1
    image: cr.hotio.dev/hotio/bazarr:nightly
    networks:
      - main
    ports:
      - 6767:6767
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/bazarr1-config:/config

  bazarr2:
    container_name: bazarr2
    image: cr.hotio.dev/hotio/bazarr:ngihtly
    networks:
      - main
    ports:
      - 6768:6767
    environment:
      - PUID=13008
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/bazarr2-config:/config

  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - main
    ports:
      - 8080:8080
      - 8118:8118
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - VPN_ENABLED=true
      - VPN_LAN_NETWORK=192.168.53.0/24
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - VPN_IP_CHECK_DELAY=5
      - VPN_IP_CHECK_EXIT=true
      - PRIVOXY_ENABLED=false
    volumes:
      - ${ROOT_DIR}/docker/qbittorrent-config:/config
      - ${SHARE_DIR}/data/torrents:/data/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

  overseerr:
    image: cr.hotio.dev/hotio/overseerr:nightly
    networks:
      - main
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=13010
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/docker/overseerr-config:/config

networks:
  main:
    driver: bridge
    external: true
