services:
# MEDIA SERVER
#  plex:
#    image: ghcr.io/hotio/plex
#    container_name: plex
#    network_mode: host
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]
#    environment:
#      - PUID=${UID}
#      - PGID=13000
#      - UMASK=002
#      - TZ=${TIMEZONE}
#      - PLEX_CLAIM_TOKEN=${PLEX_CLAIM}
#      - PLEX_ADVERTISE_URL
#      - PLEX_NO_AUTH_NETWORKS
#      - PLEX_BETA_INSTALL=false
#      - PLEX_PURGE_CODECS=true
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
#    volumes:
#      - ${CONFIG_DIR}/plex:/config
#      - ${DATA_DIR}/files:/files
#      - /dev/shm:/transcode
#    restart: unless-stopped
#
  tautulli:
    image: ghcr.io/hotio/tautulli:testing
    container_name: tautulli
    networks:
      - mediacenter
    ports:
      - 8181:8181
#    network_mode: host
#    depends_on:
#      - plex
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    restart: unless-stopped

# SERVARR
  radarr:
    image: ghcr.io/hotio/radarr:nightly
    container_name: radarr
    networks:
      - mediacenter
    ports:
      - 7878:7878
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:nightly
    container_name: sonarr
    networks:
      - mediacenter
    ports:
      - 8989:8989
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  lidarr:
    image: ghcr.io/hotio/lidarr:nightly
    container_name: lidarr
    networks:
      - mediacenter
    ports:
      - 8686:8686
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr:nightly
    container_name: prowlarr
    networks:
      - mediacenter
    ports:
      - 9696:9696
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:nightly
    networks:
      - mediacenter
    ports:
      - 6767:6767
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - mediacenter
    ports:
      - 8080:8080
      - 8118:8118
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - VPN_ENABLED=true
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.20.0/24
      - VPN_CONF=wg0
      - VPN_FIREWALL_TYPE=auto
      - VPN_NAMESERVERS=wg
      - VPN_IP_CHECK_DELAY=5
      - VPN_IP_CHECK_EXIT=true
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}/torrents:/media/torrents
      - ${DOWNLOAD_DIR}/torrents:/download/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

  qbitmanage:
    image: ghcr.io/hotio/qbitmanage
    container_name: qbitmanage
    networks:
      - mediacenter
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/qbitmanage:/config
      - ${DATA_DIR}/torrents:/media/torrents
      - /home/jnbolsen/docker-config/qbittorrent/data/BT_backup:/torrentdir
    restart: unless-stopped

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    networks:
      - mediacenter
    user: 13007:13000
    ports:
      - 2468:2468
    volumes:
      - ${CONFIG_DIR}/cross-seed:/config
      - ${DATA_DIR}/torrents:/media/torrents
    command: daemon
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - mediacenter
    ports:
      - 8081:8080
    environment:
      - PUID=13012
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/sabnzbd:/config
      - ${DATA_DIR}/usenet:/media/usenet
      - ${DOWNLOAD_DIR}/usenet:/download/usenet
    restart: unless-stopped

  overseerr:
    image: ghcr.io/hotio/overseerr:nightly
    networks:
      - mediacenter
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr
    networks:
      - mediacenter
    container_name: notifiarr
    environment:
      - PUID=13010
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    ports:
      - 5454:5454
    volumes:
      - ${CONFIG_DIR}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped

networks:
  mediacenter:
    driver: bridge
