name: ezarr

services:
  tautulli:
    image: ghcr.io/hotio/tautulli:testing
    container_name: tautulli
    ports:
      - 8181:8181
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr:nightly
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DATA_DIR}:/media
    depends_on:
      - qbittorrent
      - prowlarr
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:nightly
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DATA_DIR}:/media
    depends_on:
      - qbittorrent
      - prowlarr
    restart: unless-stopped

  lidarr:
    image: ghcr.io/hotio/lidarr:nightly
    container_name: lidarr
    ports:
      - 8686:8686
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${DATA_DIR}:/media
    depends_on:
      - qbittorrent
      - prowlarr
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr:nightly
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:nightly
    ports:
      - 6767:6767
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - 8080:8080
      - 8118:8118
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - VPN_ENABLED=true
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.20.0/24
      - VPN_CONF=wg0
      - VPN_FIREWALL_TYPE=auto
      - VPN_NAMESERVERS=wg
      - VPN_IP_CHECK_DELAY=5
      - VPN_IP_CHECK_EXIT=true
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}/torrents:/media/torrents
      - ${DOWNLOAD_DIR}/torrents:/download/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

  qbitmanage:
    image: ghcr.io/hotio/qbitmanage
    container_name: qbitmanage
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/qbitmanage:/config
      - ${DATA_DIR}/torrents:/media/torrents
      - /home/jnbolsen/docker-config/qbittorrent/data/BT_backup:/torrentdir
    depends_on:
      - qbittorrent
    restart: unless-stopped

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    user: 13007:13000
    ports:
      - 2468:2468
    volumes:
      - ${CONFIG_DIR}/cross-seed:/config
      - ${DATA_DIR}/torrents:/media/torrents
    command: daemon
    depends_on:
      - qbittorrent
    restart: unless-stopped

  overseerr:
    image: ghcr.io/hotio/overseerr:nightly
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    environment:
      - PUID=13010
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    ports:
      - 5454:5454
    volumes:
      - ${CONFIG_DIR}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped
