services:
# MEDIA SERVER
  plex:
    image: cr.hotio.dev/hotio/plex
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - ADVERTISE_IP=https://plex.jnbolsen.com
      - ALLOWED_NETWORKS=
      - PLEX_PASS=no
      - PLEX_CLAIM=${PLEX_CLAIM}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${DATA_DIR}/files:/files
      - /dev/shm/plex:/transcode
    restart: unless-stopped

  tautulli:
    image: cr.hotio.dev/hotio/tautulli:testing
    container_name: tautulli
    network_mode: host
    depends_on:
      - plex
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    restart: unless-stopped

# SERVARR
  radarr:
    image: cr.hotio.dev/hotio/radarr:nightly
    container_name: radarr
    networks:
      - mediacenter
    ports:
      - 7878:7878
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  sonarr:
    image: cr.hotio.dev/hotio/sonarr:v4
    container_name: sonarr
    networks:
      - mediacenter
    ports:
      - 8989:8989
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  lidarr:
    image: cr.hotio.dev/hotio/lidarr:nightly
    container_name: lidarr
    networks:
      - mediacenter
    ports:
      - 8686:8686
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/lidarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  readarr:
    image: cr.hotio.dev/hotio/readarr:nightly
    container_name: readarr
    networks:
      - mediacenter
    ports:
      - 8787:8787
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/readarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr:nightly
    container_name: prowlarr
    networks:
      - mediacenter
    ports:
      - 9696:9696
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:nightly
    networks:
      - mediacenter
    ports:
      - 6767:6767
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${DATA_DIR}:/media
    restart: unless-stopped

  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - mediacenter
    ports:
      - 8080:8080
      - 8118:8118
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
      - VPN_ENABLED=true
      - VPN_LAN_NETWORK=192.168.20.0/24
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - VPN_IP_CHECK_DELAY=5
      - VPN_IP_CHECK_EXIT=true
      - PRIVOXY_ENABLED=false
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DATA_DIR}/torrents:/media/torrents
      - ${DOWNLOAD_DIR}/torrents:/download/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  nzbget:
    image: cr.hotio.dev/hotio/nzbget:latest
    container_name: nzbget
    networks:
      - mediacenter
    ports:
      - 6789:6789
    environment:
      - PUID=13008
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${DATA_DIR}/usenet:/media/usenet
      - ${DOWNLOAD_DIR}/usenet:/download/usenet
    restart: unless-stopped

  overseerr:
    image: cr.hotio.dev/hotio/overseerr:nightly
    networks:
      - mediacenter
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr
    networks:
      - mediacenter
    container_name: notifiarr
    environment:
      - PUID=13010
      - PGID=13000
      - UMASK=002
      - TZ=${TIMEZONE}
    ports:
      - 5454:5454
    volumes:
      - ${CONFIG_DIR}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    restart: unless-stopped

networks:
  mediacenter:
    driver: bridge
